In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv(r"C:\Users\System -02\Downloads\Clean_01_bank_loan_applications.csv")
df.drop_duplicates()
df.columns

Index(['application_id', 'applicant_name', 'applicant_age', 'gender',
       'monthly_income', 'loan_amount_requested', 'loan_purpose',
       'employment_type', 'credit_score', 'existing_loans_count',
       'loan_tenure_months', 'interest_rate_pct', 'bank_name',
       'application_date', 'approval_status', 'default_status', 'city'],
      dtype='str')

In [4]:
df.shape

(4535, 17)

In [5]:
for col in ['city','approval_status','default_status','employment_type']:
    df[col] = df[col].str.title()

In [6]:
df['default_status'] = df['default_status'].fillna('Unknown').str.strip().str.title()
df['default_status'] = df['default_status'].str.replace('Unknown','Yes')

In [7]:
df.isnull().sum().sort_values(ascending=False).head(5)

interest_rate_pct       365
employment_type         363
existing_loans_count    362
application_id            0
default_status            0
dtype: int64

In [8]:
df[['interest_rate_pct','employment_type','existing_loans_count']].head(5)

   interest_rate_pct employment_type  existing_loans_count
0                NaN      Freelancer                   NaN
1              11.97  Business Owner                   2.0
2              12.86       Homemaker                   1.0
3              18.87             NaN                   1.0
4               9.33        Salaried                   2.0

In [9]:
df['interest_rate_pct'] = df['interest_rate_pct'].fillna(df['interest_rate_pct'].median())
df['existing_loans_count'] = df['existing_loans_count'].fillna(df['existing_loans_count'].median())

In [10]:
df.isnull().sum().sort_values(ascending=False).head(1)

employment_type    363
dtype: int64

In [11]:
df['employment_type'] = df['employment_type'].fillna(df['employment_type'].mode()[0])

In [12]:
df.describe()

,applicant_age,monthly_income,loan_amount_requested,credit_score,existing_loans_count,loan_tenure_months,interest_rate_pct
count,4535.00000,4.535000e+03,4.535000e+03,4535.000000,4535.000000,4535.000000,4535.000000
mean,42.51731,7.828160e+05,8.414247e+05,636.479162,2.001985,89.337155,15.776673
std,12.69647,2.571163e+07,1.084894e+06,149.033873,1.365898,73.823816,4.611126
min,1.00000,1.500400e+04,0.000000e+00,300.000000,0.000000,12.000000,7.510000
25%,32.00000,2.601950e+04,1.760000e+05,559.000000,1.000000,36.000000,11.970000
50%,43.00000,5.615500e+04,3.500000e+05,639.000000,2.000000,60.000000,15.690000
75%,54.00000,1.871295e+05,1.028000e+06,747.500000,3.000000,120.000000,19.545000
max,64.00000,1.000000e+09,5.691000e+06,899.000000,4.000000,240.000000,24.000000

In [13]:
df['application_date'] = pd.to_datetime(df['application_date'],format='mixed',dayfirst=True)

In [14]:
df.iloc[4:8]

,application_id,applicant_name,applicant_age,gender,monthly_income,loan_amount_requested,loan_purpose,employment_type,credit_score,existing_loans_count,loan_tenure_months,interest_rate_pct,bank_name,application_date,approval_status,default_status,city
4,LN254599,Applicant Verma,30,M,34795,337000,Personal Loan,Salaried,788,2.0,60,9.33,IndusInd Bank,2021-01-02,Approved,No,Pune
5,LN349394,Applicant Joshi,26,M,46438,216000,HOME LOAN,Homemaker,599,3.0,240,20.49,ICICI Bank,2021-01-02,Pending,Yes,Lucknow
6,LN449722,Applicant Yadav,34,M,15260,167000,Home loan,Salaried,634,2.0,180,23.15,SBI,2021-02-01,Rejected,Yes,Ahmedabad
7,LN951464,Applicant Patel,22,F,34944,95000,Car Loan,Self-Employed,621,1.0,24,18.11,ICICI Bank,2021-01-02,Approved,No,Jaipur

In [15]:
df.loc[50:52]

,application_id,applicant_name,applicant_age,gender,monthly_income,loan_amount_requested,loan_purpose,employment_type,credit_score,existing_loans_count,loan_tenure_months,interest_rate_pct,bank_name,application_date,approval_status,default_status,city
50,LN498002,Applicant Sharma,48,M,63062,727000,Medical Emergency Loan,Freelancer,709,4.0,180,18.15,Canara Bank,2021-01-15,Approved,No,Jaipur
51,LN574697,Applicant Joshi,25,M,170306,1384000,car loan,Business Owner,823,0.0,180,22.84,Kotak Mahindra,2021-01-15,Approved,No,Chennai
52,LN370876,Applicant Mehta,23,F,62921,191000,Car Loan,Business Owner,508,1.0,48,12.91,SBI,2021-01-15,Rejected,Yes,Pune

In [16]:
df['Month'] = df['application_date'].dt.month_name()

In [25]:
df.groupby('approval_status')['Month'].value_counts().sort_values(ascending=False).head(20)

approval_status  Month
Approved         May          237
                 March        231
                 January      230
                 April        228
                 June         228
                 February     200
                 August       195
                 October      193
                 September    184
                 December     183
Rejected         March        180
                 May          173
                 January      170
                 February     170
Approved         July         168
Rejected         June         164
                 April        160
Approved         November     155
Rejected         November     146
                 July         145
Name: count, dtype: int64

In [18]:
df['Year'] = df['application_date'].dt.year

In [19]:
df.groupby('Year')['approval_status'].value_counts()

Year  approval_status
2021  Approved           674
      Rejected           531
      Pending             95
2022  Approved           730
      Rejected           493
      Pending             74
2023  Approved           691
      Rejected           530
      Pending             77
2024  Approved           337
      Rejected           266
      Pending             37
Name: count, dtype: int64

In [ ]:
from sqlalchemy import create_engine
username = "postgres"
password = "nikku2004"
host = "localhost"
port = "5432"
database = "Bank"

engine = create_engine(f"postgres+psycopg2://{username}:{password}@{host}:{port}/{database}")
table_name = "Bank"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print("done")